### ISSUE TITLE
update to use libtool 2.4.7

### ISSUE THREAD

**Issue by wkliao** [Parallel-NetCDF/PnetCDF#127]
Hi, @skosukhin 

Your PR #59 fixed the libtool problem.
I think the latest libtool version 2.4.7 may have also addressed this problem. 
Thus, instead of using a customized libtool.m4 and ltmain.sh, PnetCDF can
simply uses the ones generated by libtool. I have tested this fine with
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7048.

I wonder if you could please test the master branch to see if it also works for your case?

**Comment by skosukhin** [comment]
Hi @wkliao,

As far as I can tell none of the issues addressed by #59 is fixed in libtool 2.4.7.

**Comment by wkliao** [comment]
Thanks for checking!
I also found a case that failed when using lib 2.4.7.
I will keep your patches.
