### ISSUE TITLE
Is it possible to build from a tagged version

### ISSUE THREAD

**Issue by VictorEijkhout** [Parallel-NetCDF/PnetCDF#133]
I downloaded the latest tagged tar.gz and ran `autoreconf -i` and got:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Hence the question in the subject line.

**Comment by wkliao** [comment]
Are you looking for the official releases of PnetCDF?
All official releases of PnetCDF are available in
https://parallel-netcdf.github.io/wiki/Download.html

The tagged versions are not for production use.

**Comment by VictorEijkhout** [comment]
Thanks. That configures & builds fine.
