### ISSUE TITLE
Configure fails with Intel 2024 OneAPI

### ISSUE THREAD

**Issue by VictorEijkhout** [Parallel-NetCDF/PnetCDF#136]
```
checking for Fortran libraries of /opt/intel/oneapi/mpi/2021.11/bin/mpif90...  -loopopt=1
```
and then the loader complains about that strange library.

Intel note: https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-fortran-compiler-release-notes.html

Going by that advise I run `autoreconf -i` which solves the problem despite many errors:

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
configure.ac:1523: warning: The macro 'AC_HELP_STRING' is obsolete.
configure.ac:1523: You should run autoupdate.
```

**Comment by wkliao** [comment]
If you are building PnetCDF using its github repo (which is not recommended for
production use), please clone the repo before running `autoreconf -i`. 
Below is the clone command.
```
git clone https://github.com/Parallel-NetCDF/PnetCDF.git
```

**Comment by VictorEijkhout** [comment]
No, I'm using the 1.12.3 download. It builds fine with gcc but not the latest intel.

**Comment by wkliao** [comment]
This issue has been reported in #94. The fix will appear in the next release.

If you want to work on 1.12.3, then please edit file configure.ac
and delete line 10 below and run `autoreconf -if`.
```
AC_REVISION([m4_esyscmd_s([git describe --always])])
```

**Comment by VictorEijkhout** [comment]
The new version seems to solve it. Thanks.
