### ISSUE TITLE
configure cannot be created on Intel Knights Landing

### ISSUE THREAD

**Issue by naromero77** [Parallel-NetCDF/PnetCDF#20]
The usual manner of generating configure is:
```
aclocal -I./m4
autoconf
automake --add-missing
```
However, this does not work on the Intel Knights Landing. Here is the error that I get:
```
[naromero@hyperion PnetCDF-1.10.0]$ aclocal -I./m4 
[naromero@hyperion PnetCDF-1.10.0]$ autoconf
[naromero@hyperion PnetCDF-1.10.0]$ automake --add-missing
configure.ac:33: installing './scripts/install-sh'
configure.ac:313: error: required file './scripts/ltmain.sh' not found
configure.ac:33: installing './scripts/missing'
benchmarks/C/Makefile.am: installing './scripts/depcomp'
parallel-tests: installing './scripts/test-driver'
configure.ac:22: error: required file 'src/include/config.h.in' not found
```

**Comment by wkliao** [comment]
I assume you cloned the source codes from the github repo, instead of using the official release tar ball. After cloning the source codes from the github repo, you need to run command `autoreconf -i` first. It will create all necessary for you to run `configure` command.

**Comment by naromero77** [comment]
No, I used the official release tar ball here.
https://github.com/Parallel-NetCDF/PnetCDF/releases/tag/v1.10.0

**Comment by wkliao** [comment]
That one is simply a tag, not an official release. All official releases can be downloaded in http://cucis.ece.northwestern.edu/projects/PnetCDF/download.html

Once you un-tar the tar ball, you can run configure command without first running aclocal, autoconf, or automake.
