### ISSUE TITLE
configure get error in AIX(ksh)

### ISSUE THREAD

**Issue by poohRui** [Parallel-NetCDF/PnetCDF#21]
While I run this commond in parallel-netcdf-1.10.0
```
./configure --prefix=/gza/u/xiaohui/g6/code_test/PnetCDF --host power
```
I got this error
```
checking if Fortran compiler is NAG... ./configure[28135]: conftest.ver: bad file unit number
```
and can not get makefile so on
I wonder how to solve it
Thank you!

**Comment by wkliao** [comment]
The error message indicates your MPI Fortran compiler has a problem with command-line argument `-V`. Please provide the link to your `config.log` file and I will take a look.

**Comment by poohRui** [comment]
Thank you for your reply.
Here is the link:
https://github.com/poohRui/doc/blob/master/config.log

**Comment by wkliao** [comment]
Could you please apply the following patch and let me know if it works?
```
 --- a/acinclude.m4
 +++ b/acinclude.m4
 @@ -1578,8 +1578,7 @@ dnl
  AC_DEFUN([UD_CHECK_FC_NAG],[
      AC_CACHE_CHECK([if Fortran compiler is NAG], [ac_cv_fc_compiler_nag],
      [ac_cv_fc_compiler_nag=no
 -     eval $MPIF90 -V </dev/null >& conftest.ver
 -     _FC_VENDOR=`head -c 3 conftest.ver`
 +     _FC_VENDOR=`eval $MPIF90 -V 2>&1 | head -c 3`
       if test "x${_FC_VENDOR}" = xNAG ; then
          ac_cv_fc_compiler_nag=yes
       fi
 -     ${RM} -f conftest.ver
       unset _FC_VENDOR
      ])
  ])
```
I have never tested PnetCDF on ksh. It appears that ksh's stdout and stderr redirection is different from bash.

**Comment by poohRui** [comment]
I think you mean this file.
Here is the link:
https://github.com/poohRui/someIssues/blob/master/acinclude.m4

**Comment by wkliao** [comment]
Yes.

**Comment by wkliao** [comment]
It appears ksh does not work well with automake. A bug report of configure hanging can be found in
http://gnu-automake.7480.n7.nabble.com/bug-20244-automake-1-15-tests-environment-fd-redirect-hangs-on-RHEL-6-6-CentOS-6-6-w-ksh-2012-08-01-tt21812.html

**Comment by poohRui** [comment]
Thank you!
After I changed the shell to bash, The error disappeared.

**Comment by wkliao** [comment]
Close this issue, as ksh is not supported.
It can be reopened, if ksh is to be supported in the future.
