### ISSUE TITLE
Releases don't include needed files for autoconf/automake builds

### ISSUE THREAD

**Issue by edhartnett** [Parallel-NetCDF/PnetCDF#41]
Instead of letting github assemble your build, you need to use "make dist" to create the tarball, and upload those binaries to your github release page. If you do that, you will get a configure script, and all the other files necessary to support an autotools build.

If not, you just get the configure.ac and Makefile.am files that are in git. These are OK for a developer who has autotools installed, and can run autoreconf -i, but the idea is that the average user does not have to have these tools, and just runs the configure script.

**Comment by wkliao** [comment]
README.md has already explained the difference of releases and codes in this repo..

**Comment by edhartnett** [comment]
OK, so I see you are doing this on purpose. ;-) I will close the ticket.
