### ISSUE TITLE
<< "mpiicc" fails sanity check >>

### ISSUE THREAD

**Issue by icamps** [Parallel-NetCDF/PnetCDF#43]
Hello,

I am trying to compile PnetCDF using the latest Intel Fortran compiler (19.0.3.199 Build 20190206) and MPI (Version 2019 Update 3 Build 20190214) and I am getting the following error:

`configure: error: in /home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0':
configure: error: C preprocessor "mpiicc" fails sanity check
See config.log' for more details`

Attached is the log file.

I´ll appreciate any help regarding this issue.

Thanks in advance,

Camps

[config.log](https://github.com/Parallel-NetCDF/PnetCDF/files/3059943/config.log)

**Comment by wkliao** [comment]
Sometimes Intel C preprocessor requires `-E` option. Can you try the following configure command?
```
  $ ./configure --prefix=/software/LIBS/pnetcdf-1.11.0 MPICC=mpiicc CPP="mpiicc -E"
```

FYI. Your config.log shows the following configure command was used.
```
  $ ./configure --prefix=/software/LIBS/pnetcdf-1.11.0 CPPFLAGS=-fPIC -I/software/LIBS/hdf5-1.8.12/include -I/software/LIBS/zlib-1.2.8/include LDFLAGS=-L/software/LIBS/hdf5-1.8.12/lib -Wl,-rpath=/software/LIBS/hdf5-1.8.12/lib -L/software/LIBS/zlib-1.2.8/lib -Wl,-rpath=/software/LIBS/zlib-1.2.8/lib
```
You do not need those HDF5 related paths in CFLAGS and and LDFLAGS, if you are configuring PnetCDF with default setting.  Besides, if you would like to build a shared library, add `--enable-shared` to the configure command line (no need of -fPIC in CFLAGS).

**Comment by icamps** [comment]
Dear @wkliao, thank you very much.  It configures without any message but, when installing `(make install)` I got:
(note I used you compiling recommendation)

Making install in src
make[1]: Entering directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src'
Making install in include
make[2]: Entering directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/include'
make[3]: Entering directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/include'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/software/LIBS/pnetcdf-1.11.0/include'
 /usr/bin/install -c -m 644 pnetcdf.h '/software/LIBS/pnetcdf-1.11.0/include'
make[3]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/include'
make[2]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/include'
Making install in dispatchers
make[2]: Entering directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/dispatchers'
m4  -B10000 -DPNETCDF -I../../m4 attr_getput.m4 >attr_getput.c
/bin/bash: m4: command not found
Makefile:732: recipe for target 'attr_getput.c' failed
make[2]: *** [attr_getput.c] Error 127
make[2]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/dispatchers'
Makefile:457: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src'
Makefile:514: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by wkliao** [comment]
This error says the utility program `m4` required by PnetCDF is not available on your system. You may want to install `m4` on your system. `GNU m4` is available in https://www.gnu.org/software/m4/m4.html

**Comment by wkliao** [comment]
Please provide your new config.log file. Checking the availability of `m4` should be done at the configure time. If it is not available, I expect configure to abort.

**Comment by icamps** [comment]
The libraries were successfully created (I installed m4 from the repositories). Other errors appear:

make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/libs'
make[2]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/libs'
Making install in utils
make[2]: Entering directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils'
Making install in ncmpigen
make[3]: Entering directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen'
  CCLD     ncmpigen
genlib.o: In function `gen_netcdf':
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:131: undefined reference to `ncmpi_put_att_ulonglong'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:126: undefined reference to `ncmpi_put_att_longlong'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:121: undefined reference to `ncmpi_put_att_uint'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:116: undefined reference to `ncmpi_put_att_ushort'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:111: undefined reference to `ncmpi_put_att_uchar'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:106: undefined reference to `ncmpi_put_att_double'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:101: undefined reference to `ncmpi_put_att_float'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:96: undefined reference to `ncmpi_put_att_int'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:91: undefined reference to `ncmpi_put_att_short'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:86: undefined reference to `ncmpi_put_att_text'
/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen/genlib.c:81: undefined reference to `ncmpi_put_att_schar'
Makefile:534: recipe for target 'ncmpigen' failed
make[3]: *** [ncmpigen] Error 1
make[3]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils/ncmpigen'
Makefile:526: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src/utils'
Makefile:457: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/icamps/temp/SIESTA/extras/pnetcdf-1.11.0/src'
Makefile:514: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
[config.log](https://github.com/Parallel-NetCDF/PnetCDF/files/3060849/config.log)

**Comment by wkliao** [comment]
The config.log still complains about the m4.
Could you please do a clean build? i.e. by running commands below.
```
make distclean
./configure --prefix=/software/LIBS/pnetcdf-1.11.0 MPICC=mpiicc CPP="mpiicc -E"
make
```

**Comment by icamps** [comment]
Everything run smoothly now! No errors.

Thank you very much.

**Comment by wkliao** [comment]
Glad to hear that. Thanks for reporting the error.
I will add a note to file doc/README.INTEL about this issue.
