### ISSUE TITLE
Wrong comparison criteria in testcase/tst_info.c

### ISSUE THREAD

**Issue by hzfywhn** [Parallel-NetCDF/PnetCDF#54]
In line 150-156, the comparison logic looks like this:

```
#ifdef ENABLE_SUBFILING
        if (strcasecmp("enable", value))
            printf("Error: pnetcdf_subfiling expect \"enable\" but got \"%s\"\n", value);
#else
        if (strcasecmp("disable", value))
            printf("Error: pnetcdf_subfiling expect \"disable\" but got \"%s\"\n", value);
#endif
```

But I do think it should be the other way.

**Comment by wkliao** [comment]
What other way should it be?

The logic here is when subfiling feature is enabled, the hint 'pnetcdf_subfiling=enable' set in the environment variable PNETCDF_HINTS earlier in line 64 should go into the MPI info object. Thus the hint's value is expected to be 'enable'. On the other hand, when subfiling feature is not enabled, the hint pnetcdf_subfiling should have value 'disable'.

**Comment by hzfywhn** [comment]
In my logic, when subfiling is enabled, `strcasecmp("enable", value)` evaluates to true, then it shouldn't print the error message.

**Comment by wkliao** [comment]
Please check the man page of function `strcasecmp`.
It returns 0 when the two strings match (ignoring the case of the characters).

**Comment by hzfywhn** [comment]
Oh, I mixed c conventions with other languages. Thank you for the explanation!
