### ISSUE TITLE
Test failure on mips64el: clobber test

### ISSUE THREAD

**Issue by amckinstry** [Parallel-NetCDF/PnetCDF#56]
When built on 64-bit mips (el), we see a test failure:

https://buildd.debian.org/status/fetch.php?pkg=pnetcdf&arch=mips64el&ver=1.12.0-1&stamp=1570052714&raw=0

This is for version 1.12.0. Previous versions passed.

**Comment by wkliao** [comment]
Could you provide the log file "test/testcases/noclobber.log" ?

**Comment by wkliao** [comment]
Looks like the error has been fixed in the later releases.

Debian Package Auto-Building
https://buildd.debian.org/status/package.php?p=pnetcdf
