### ISSUE TITLE
Does not build with GCC 10

### ISSUE THREAD

**Issue by michaelkuhn** [Parallel-NetCDF/PnetCDF#61]
When trying to build Parallel-NetCDF 1.12.1 using GCC 10, I get a lot of these errors:
```
getput_vard.fh:1988:86:

 1988 |      nf90mpi_get_vard_7D_EightByteInt_all = nfmpi_get_vard_all(ncid, varid, filetype, buf, bufcount, buftype)
      |                                                                                      1
......
 2324 |      nf90mpi_get_vard_7D_text_all = nfmpi_get_vard_all(ncid, varid, filetype, buf(1,1,1,1,1,1,1), bufcount, buftype)
      |                                                                              2        
Error: Type mismatch between actual argument at (1) and actual argument at (2) (INTEGER(8)/CHARACTER(*)).
```
Adding `-fallow-argument-mismatch` to `FFLAGS` and `FCFLAGS` works around the problem.

**Comment by wkliao** [comment]
Thanks. It  appears adding that compile flag is also suggested by [netcdf-fortran #212](https://github.com/Unidata/netcdf-fortran/issues/212) and [MPICH](https://lists.mpich.org/pipermail/discuss/2020-January/005863.html). A list of software affected by this is collected on [homebrew #54364](https://github.com/Homebrew/homebrew-core/pull/54364).

**Comment by wkliao** [comment]
Pull request #63 is created to address this issue and has been merged to the master branch.
Thanks @michaelkuhn for reporting.
