### ISSUE TITLE
Release tarballs omit Readme.md

### ISSUE THREAD

**Issue by StefanBruens** [Parallel-NetCDF/PnetCDF#66]
https://github.com/Parallel-NetCDF/PnetCDF/blob/43e692833039183cdd0a9bc0757f0f201fcad949/Makefile.am#L21

**Comment by wkliao** [comment]
This is intended.
The contents of README.md contain information about this repository.
Source codes in this repo is under development. On the other hand,
README contains the information about the official releases of PnetCDF.
