### ISSUE TITLE
configure fails with intel OneAPI 2022.2.0

### ISSUE THREAD

**Issue by bourdin** [Parallel-NetCDF/PnetCDF#94]
Configure fails when using the latest version of the intel OneAPI compilers on a plain RHEL7 linux box. I don't understand where the `-loopopt-1` options gets pulled from.

[config.log](https://github.com/Parallel-NetCDF/PnetCDF/files/10127780/config.log)

Any idea?

**Comment by wkliao** [comment]
According to this [post](https://community.intel.com/t5/Intel-Fortran-Compiler/ifx-2021-1-beta04-HPC-Toolkit-build-error-with-loopopt/m-p/1184181), it seems the problem can be resolved by autoconf 2.7.0 or newer versions. Could you give it a try? Note once it is installed, please run command `"autoreconf -i"` before your `configure` command.

**Comment by bourdin** [comment]
Thanks. It worked (modulo having to build a newer version of autoconf).
